AWSTemplateFormatVersion: '2010-09-09'

Resources:
  MyECRPublicRegistry:
    Type: AWS::ECR::PublicRepository
    Properties:
      RepositoryName: my-public-ecr-repo
      RepositoryPolicyText:
        Version: '2008-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ['codebuild.amazonaws.com', 'codepipeline.amazonaws.com']
            Action: ['ecr:GetDownloadUrlForLayer', 'ecr:BatchCheckLayerAvailability', 'ecr:BatchGetImage', 'ecr:InitiateLayerUpload', 'ecr:UploadLayerPart', 'ecr:CompleteLayerUpload', 'ecr:PutImage']
          - Effect: Allow
            Principal:
              AWS: '*'
            Action: 'ecr:*'

